apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: hcp-20
  namespace: clusters
spec:
  clusterName: hcp-20
  management:
    autoRepair: true
    replace:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      strategy: RollingUpdate
    upgradeType: Replace
  nodeDrainTimeout: 0s
  nodeVolumeDetachTimeout: 0s
  platform:
    type: KubeVirt
    kubevirt:
      attachDefaultNetwork: true
      compute:
        cores: 4
        memory: 8Gi
        qosClass: Burstable
      networkInterfaceMultiqueue: Enable
      rootVolume:
        persistent:
          size: 32Gi
        type: Persistent
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.19.21-x86_64
  replicas: 1
